[project]
name = "my-stock-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "akshare>=1.16.79",
    "fastmcp>=2.2.0",
    "pandas>=2.2.3",
]
